"""Added Suppliers Model

Revision ID: f8b6506d7ca4
Revises: 2c9d15e4eb91
Create Date: 2023-09-07 08:32:57.456597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b6506d7ca4'
down_revision = '2c9d15e4eb91'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'suppliers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('contact_info', sa.String(), nullable=True),  # Modify this as needed
        sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
